### ISSUE TITLE
RequestEntityTooLargeException

### ISSUE THREAD

**Issue by tho-can-code** [freeletics/fl-snowflake-lambda-layer#1]
Hi @amrqura ,

Thank you for your repo. I'm trying it but I get the error:

**An error occurred (RequestEntityTooLargeException) when calling the PublishLayerVersion operation: Request must be smaller than 69905067 bytes for the PublishLayerVersion operation**

Would you please help me in this case?

Thank you so much.

**Comment by fluxquantum** [comment]
@thosieucoi Hi, were you able to find a way around the lambda zip and layer size quota? If so, may you share your experience? I currently have to include it in my lambda artifact which prevents me from leveraging the console IDE, as making it a layer is too large unfortunately. Thanks for your time.

**Comment by tho-can-code** [comment]
@fluxquantum I solved it by using lower version (snowflake-connector-python version 1.9.1).
